### ISSUE TITLE
sbt run is not working on the gitter8 template, on MacOS, using scala3

### ISSUE THREAD

**Issue by ahoy-jon** [univalence/zio-spark#323]
(from Carlolis on ZIO/Discord)

```bash
sbt new univalence/zio-spark.g8 --useScala3=true
cd zio-spark-project
jenv local 11
sbt run # [info] welcome to sbt 1.8.0 (Homebrew Java 11.0.16)
```

result :
```
Exception in thread "sbt-bg-threads-1" java.lang.ExceptionInInitializerError
    at example.SimpleApp.main(Hello.scala)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at sbt.Run.invokeMain(Run.scala:143)
    at sbt.Run.execute$1(Run.scala:93)
    at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
    at sbt.Run$.executeSuccess(Run.scala:186)
    at sbt.Run.runWithLoader(Run.scala:120)
    at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1980)
    at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1919)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    at scala.util.Try$.apply(Try.scala:213)
    at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:366)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
    at example.SimpleApp$.read(Hello.scala:18)
    at example.SimpleApp$.<clinit>(Hello.scala:26)
```

**Comment by ahoy-jon** [comment]
I am taking a quick look at it. @dylandoamaral if you know what it is

**Comment by ahoy-jon** [comment]
https://github.com/univalence/zio-spark.g8/blob/7d2fa97fbaaef3e6bc3f14e927a1d408cfa05718/src/main/g8/src/main/scala/example/Hello.scala#L20

It doesn't seem to work with other versions of Java, using only `sbt run`.
Changing it to 
```diff
Index: src/main/scala/example/Hello.scala
===================================================================
diff --git a/src/main/scala/example/Hello.scala b/src/main/scala/example/Hello.scala
--- a/src/main/scala/example/Hello.scala	(revision 8eea9f637fabd9219efc5e6bfad27607c086c181)
+++ b/src/main/scala/example/Hello.scala	(date 1673325783674)
@@ -14,9 +14,11 @@
 
 
   def read: SIO[DataFrame] =
-    SparkSession.read.schema[Person].withHeader.withDelimiter(";").csv(
-      getClass.getResource("data.csv").getPath
-    )
+    SparkSession.read.schema[Person]
+      .withHeader
+      .withDelimiter(";")
+      .csv("./src/main/resources/data.csv")
+
 
   def job(inputDs: DataFrame) = inputDs.as[Person].headOption
 

```
